language: node_js
node_js:
  - "6"
  
branches:
  only:
  - master
  
# Yarn is optional. If Yarn is unwanted use "npm install" instead.
install:
  - npm install -g yarn
  - yarn

before_script:
  - npm prune

script:
  - npm run build

notifications:
  email: false